bookings/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('mountain_lodge/', views.MountainLodgeView.as_view(), name='mountain_lodge'),
    path('fir_pine_nest/', views.FirPineNestView.as_view(), name='fir_pine_nest'),
    path('create_profile/', views.CreateProfileView.as_view(), name='create_profile'), 
    path('make_reservation/', views.MakeReservationView.as_view(), name='make_reservation'), 
    path('edit_reservation/<booking_uuid>', views.EditReservationView.as_view(), name='edit_reservation'), 
    path('delete_reservation/<booking_uuid>', views.DeleteReservation.as_view(), name='delete_reservation'),
    path('manage_reservation/', views.ManageReservation.as_view(), name='manage_reservation'),
    
]

luxelandstays/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.views.static import serve
from .settings import STATIC_ROOT
from bookings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/profile/", views.CreateProfileView.as_view()),
    path('', include('bookings.urls'), name='home'),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}), 
]

bookings/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

STATUS = ((0, "Reservation Requested"), (1, "Reservation Accepted"))

class Reservation(models.Model):
    reservation_id = models.UUIDField (
        primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_reservations")
    check_in = models.DateField(auto_now=False)
    check_out = models.DateField(auto_now=False)
    guest_count = models.IntegerField()
    reservation_notes = models.TextField(max_length=300, blank=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-check_in']
        

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_number = models.CharField(max_length=11)

    def __str__(self):
        return str(self.user)

bookings/forms.py
from .models import Reservation, UserProfile
from django import forms
from django.forms import ModelForm, CharField, TextInput



class UpdateReservation(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ('check_in', 'check_out', 'guest_count', 'reservation_notes')


class EditUserProfile(forms.ModelForm):
    phone_number = CharField(widget=TextInput(attrs={'type': 'number'}))
    class Meta:
        model = UserProfile
        fields = ('name', 'email', 'phone_number')


class CreateProfile(forms.Form):
    name = forms.CharField(max_length= 50)
    email = forms.EmailField(max_length= 100)
    phone_number = forms.ImageField(max_length= 11)

bookings/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
# Import Djano generic library
from django.views import generic, View
from django.views.generic import TemplateView, DeleteView
from django.urls import reverse_lazy
# Import Reservation model from models
from .models import Reservation, UserProfile
from .forms import UpdateReservation, EditUserProfile 


class HomeView(TemplateView):
    template_name = "index.html"


class AboutView(TemplateView):
    template_name = "about.html"


class ContactView(TemplateView):
    template_name = "contact.html"


class MountainLodgeView(TemplateView):
    template_name = "mountain_lodge.html"


class FirPineNestView(TemplateView):
    template_name = "fir_pine_nest.html"


class EditReservationView(TemplateView):
    template_name = "edit_reservation.html"


class DeleteReservation(DeleteView):
    model = Reservation
    pk_url_kwarg = "booking_uuid"
    success_url = reverse_lazy("manage_reservation")
    template_name = "delete_reservation.html"


class ManageReservation(generic.ListView):
    model = Reservation
    queryset = Reservation.objects.all()
    template_name = "manage_reservation.html"
    paginate_by = 5

    def get_queryset(self):
        return Reservation.objects.filter(user_id=self.request.user)


class CreateProfileView(TemplateView):
    template_name = "create_profile.html"

    def get (self, request, *args, **kwargs):
        return render(
            request,
            "create_profile.html",
        )

    def post(self, request):
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone_number")

        CreateUserProfile = UserProfile.objects.create(
            name=name,
            email=email,
            phone_number=phone,
            user=request.user

        )

        CreateUserProfile.save()

        return redirect(reverse('home'))


class MakeReservationView(TemplateView):
    template_name = "make_reservation.html"

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "make_reservation.html"
        )

    def post(self, request):
        check_in_date = request.POST.get("check_in_date")
        check_out_date = request.POST.get("check_out_date")
        number_of_guests = request.POST.get("number_of_guests")
        notes = request.POST.get("notes")

        make_reservation = Reservation.objects.create(
            check_in=check_in_date,
            check_out=check_out_date,
            guest_count=number_of_guests,
            user=request.user,
            reservation_notes=notes
        )

        make_reservation.save()

        return redirect(reverse('manage_reservation'))

templates/about.html
{% extends "base.html" %}

{% block content %}

<header>
    <div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row">
                <img class="w-100 mx-auto" id="homepage_image"
                    src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648026512/pexels-pixabay-358532_l8kb1a.jpg"
                    alt="main_image">
            </div>    
        </div>
</header>

<div class="description">
    <h1>LUXE LANDS SECRET STAYS</h1>
    <p>Situated in the heart of the tranquil and idilic Austrian mountains,<br>Luxe Land Secret Stays offers a truly unique luxury cabin experience.<br>In the search for something a bit more luxe? You've come to the right place.</p>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <title>Luxe Land Stays</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navigation -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color:#B4D2D9;">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">
          <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648057796/LUXE_LAND_2_r0npbx.png" alt="logo-image" style="max-width: 40px; max-height: 60px"></img></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Luxe Cabins
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="background-color:#B4D2D9;">
                  <li><a class="dropdown-item" href="{% url 'mountain_lodge' %}">Mountain Lodge</a></li>
                  <li><a class="dropdown-item" href="{% url 'fir_pine_nest' %}">Fir Pine Nest</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
              </li>

              {% if user.is_authenticated %}

              <li class="nav-item px-2">
                <a class="nav-link {{ manage_reservation_active }}" href="{% url 'manage_reservation' %}">Manage
                    Reservation</a>
               </li>

               <li class="nav-item px-2">
                <a class="nav-link {{ make_reservation_active }}" href="{% url 'make_reservation' %}">Make
                    Reservation</a>
               </li>

               <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
               </li>

              {% else %}

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>

              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

      <main class="flex-shrink-0 main-bg">

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
      </main>

      <!-- Footer -->
      <footer class="footer mt-auto text-center" style="background-color:#B4D2D9;">
        <a href="https://facebook.com" target="_blank" rel="noopener"
            aria-label="visit our Facebook page (opens in a new page)"><i class="fab fa-facebook"></i></a>
        <a href="https://twitter.com" target="_blank" rel="noopener"
            aria-label="visit our Twitter page (opens in a new page)"><i class="fab fa-twitter"></i></a>
        <a href="https://instagram.com" target="_blank" rel="noopener"
            aria-label="visit our Instgram page (opens in a new page)"><i class="fab fa-instagram"></i></a>
          <section class="mb-4">
            <p>1 Mount View<br>Slope Side<br>Austria</p>
          </section>
    </footer>
    
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="container"> <div class=" text-center mt-5 ">
    <h1>Get In Touch</h1>
</div>

<div class="col-md-5 col-12 mx-auto py-5">
    <form method="POST" action="https://formdump.codeinstitute.net/">
        <label for="full_name" class="form-label">Full Name</label>
        <input type="text" class="form-control text_input" name="full_name" id="full_name"
            value="{{ user.userprofile.first_name }} {{ user.userprofile.last_name }}" required>

        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control text_input" name="email_address" id="email"
            value="{{ user.email }}" required>

        <label for="message">Your message</label>
        <textarea class="form-control" name="message" id="message" rows="3" required></textarea>

        <button type="submit" class="btn custom-red text-white mx-auto d-block my-3">
            Submit Message
        </button>
    </form>
</div>
</div>

{% endblock %}

templates/create_profile.html
{% extends "base.html" %}

{% block content %}

<!--
<div class="w-50 mx-auto py-5">
-->
<div class="container py-5">
	<h1>Sign Up</h1>
	<form method="POST">
		{% csrf_token %}               
		<button class="btn btn-primary" type="submit">Create Profile</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>


{% endblock %}

templates/delete_reservation.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
<div class="w-75 mx-auto py-5">
    <form action="." method="POST">
        {% csrf_token %}

        <h3>Do you want to cancel the reservation "{{ reservation.reservation_id }}"?</h3>

        <button class="btn custom-red text-white" type="submit">Yes</button>

        <a class="btn custom-red text-white" href="{% url 'manage_reservation' %}">
            Cancel
        </a>
    </form>
</div>
{% else %}

Please login to cancel your booking

{% endif %}

{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

templates/edit_reservation.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
	<h1>Edit your reservation</h1>
	<form method="POST">
		{% csrf_token %} 
        <div>
            <label>Check In Date</label><br>
            <input name="check_in_date" type="date" required>
        </div>  
        <div>
            <label>Check Out Date</label><br>
            <input name="check_out_date" type="date" required>
        </div>    
        <div>
            <label>Number of guests</label><br>
            <input name="number_of_guests" type="number" required>
        </div>  
        <div>
            <label>Notes</label><br>
            <textarea name="notes" required></textarea>
        </div>         
		<button class="btn btn-primary" type="submit">Make reservation</button>
	</form>
</div>


{% endblock %}

templates/fir_pine_nest.html
{% extends "base.html" %}

{% block content %}

<header>
    <div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row">
                <img class="w-100 mx-auto" id="homepage_image"
                    src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647965021/pexels-valeriia-miller-2527556_xix38e.jpg"
                    alt="main_image">
            </div>    
        </div>
</header>

    <div class="description">
        <h1>FIR PINE NEST</h1>
        <p>Fir Pine Nest Cabin is our cosy cabin for two situated right in the heart of the Austrian Alpes.<br>The property is designed for couples with one en-suite master bedroom, perfect for romantic getaways.<br> Surrounded by blissfull nature, this beautifully designed snug has a list of luxuries including a locally producted organic hamper on arrival for that little bit of luxe.</p>
    </div>

    <div class="button-container">
        <div class="orange-button">
        <a href="{% url 'account_login' %}" class="btn btn-info" id="book-button" role="button">MAKE A BOOKING</a>
        </div>
    </div> 
    
    <div class="container features" id="room-gallery-background">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648055634/pexels-pavel-danilyuk-6549839_vq3nlz.jpg" class="img-fluid">
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648026503/nachelle-nocom-51adhgg5KkE-unsplash_vzeysp.jpg" class="img-fluid">
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648026508/pexels-rachel-claire-4825713_lkweqm.jpg" class="img-fluid">
            </div>

              
        </div>
    </div>


    


{% endblock %}
   

templates/index.html
{% extends "base.html" %}

{% block content %}

<header>
    <div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row">
                <img class="w-100 mx-auto" id="homepage_image"
                    src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647943496/pexels-marlon-martinez-1450208_zfkl2q.jpg"
                    alt="homepage_image">
            </div>    
        </div>
</header>

    <div class="description">
        <h1>A TRULY LIFE LUXE EXPERIENCE</h1>
    </div> 
    
    <div class="container features">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647964884/pexels-angela-cavina-2380249_asnhst.jpg" class="img-fluid">
                <h3 class="cabin">MOUNTAIN LODGE</h3>
                <p>With three bedrooms and a hot tub, this beautiful cabin is all you need to switch off and unwind. Perfect for families and small groups.</p>
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647964083/pexels-adriaan-greyling-754268_qlu13r.jpg" class="img-fluid">
                <h3 class="cabin">FIR PINE NEST</h3>
                <p>Perfect for a romantic escape, this luxury one bedroom cabin has all you need to hide away. Set within the blissful backdrop of the Austrian mountains. </p>
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647964926/antonio-grosz-iwzRmK6vNLg-unsplash_zh07aw.jpg" class="img-fluid" href="contact.html">
                <h3 class="cabin">FURTHER INFORMATION</h3>
                <p>Luxe Land Secret Stays offer a truly unique luxury experience for the traveller looking for that little bit of extra luxe. </p>
            </div>
        </div>
    </div>


{% endblock %}

templates/make_reservation.html
{% extends "base.html" %}

{% block content %}

<div class="container py-5">
	<h1>Make a reservation</h1>
	<form method="POST">
		{% csrf_token %} 
        <div>
            <label>Check In Date</label><br>
            <input name="check_in_date" type="date" required>
        </div>  
        <div>
            <label>Check Out Date</label><br>
            <input name="check_out_date" type="date" required>
        </div>    
        <div>
            <label>Number of guests</label><br>
            <input name="number_of_guests" type="number" required>
        </div>  
        <div>
            <label>Notes</label><br>
            <textarea name="notes" required></textarea>
        </div>         
		<button class="btn btn-primary" type="submit">Make reservation</button>
	</form>
</div>


{% endblock %}

templates/manage_reservation.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2 class="text-center text-decoration-underline py-3">Manage My Reservation</h2>
        </div>
    </div>

    {% for reservation in reservation_list %}
    <div class="row py-5">
        <div class="col-12">
            <div class="card bg-dark">
                <div class="card-body">
                    <h5 class="card-title">Booking Reference: {{ reservation.reservation_id }}</h5>
                    <p class="card-text">
                        Booking Status: {% if reservation.status == 1 %}
                        Booking Accepted
                        {% else %}
                        Booking Requested
                        {% endif %}
                    </p>
                </div>

                <ul class="list-group list-group-flush" id="card-details">
                    <li class="list-group-item text-white" style="background-color:#B4D2D9;">Check In Date : {{ reservation.check_in }}</li>
                    <li class="list-group-item text-white" style="background-color:#B4D2D9;">Check Out Date: {{ reservation.check_out }}</li>
                    <li class="list-group-item text-white" style="background-color:#B4D2D9;">Guest Count: {{ reservation.guest_count }}</li>
                </ul>

                <div class="card-body d-flex">
                    <a href="{% url 'edit_reservation' reservation.reservation_id %}" class="card-link btn text-white">
                        Change Reservation Details
                    </a>
                    <a href="{% url 'delete_reservation' reservation.reservation_id %}" class="card-link btn text-white">
                        Cancel Reservation
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock %}

templates/mountain_lodge.html
{% extends "base.html" %}

{% block content %}

<header>
    <div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="row">
                <img class="w-100 mx-auto" id="homepage_image"
                    src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648054391/pexels-simon-berger-688660_bmjrum.jpg"
                    alt="main_image">
            </div>    
        </div>
</header>

    <div class="description">
        <h1>MOUNTAIN LODGE</h1>
        <p>Mountain Lodge is approached down a country track hidden within the beautiful mountains and trees of the region.<br> Enjoy the escapism and luxury this cabin has to offer, with a private hot tub overlooking the mountains,<br>surrounded by wildlife and nature, it has everything you need for a truly luxe escape.</p>
    </div>

    <div class="button-container">
        <div class="orange-button">
        <a href="{% url 'account_login' %}" class="btn btn-info" id="book-button" role="button">MAKE A BOOKING</a>
        </div>
    </div> 
    
    <div class="container features" id="room-gallery-background">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1647958891/pexels-ron-lach-9211817_s2jzav.jpg" class="img-fluid">
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648026509/gleb-albovsky-a-0Qsar9rBg-unsplash_fos2mj.jpg" class="img-fluid">
            </div>
            
            <div class="col-lg-4 col-md-4 col-sm-12" id="cabin-image">
                <img src="https://res.cloudinary.com/dvppi5ims/image/upload/v1648026511/pexels-roberto-nickson-2659629_anligc.jpg" class="img-fluid">
            </div>

              
        </div>
    </div>


    


{% endblock %}
   